"use strict";

let oblique = {
    prompts: [
        "You have a title, a strategy and two images. Make something!",
        "Use what you see on this page to create something new.",
        "Here is the moodboard for your next thing. Now make it!",
        "Does the title inspire you more than the images do? Go with that then!",
        "That second image is pretty cool. I bet you could make it cooler though.",
        "Good ideas need hard work to be found. Now make something out of what you see here.",
    ],
    strategies: [
        'Abandon favorite tools',
        'Be dirty',
        'Breathe more deeply',
        'Decorate, decorate',
        'Define an area as "safe" and use it as an anchor',
        'Destroy the most important thing',
        'Only straight lines',
        'Emphasize differences',
        'Emphasize repetitions',
        'Emphasize the shadows',
        'Look at a very small object, look at its centre',
        'Look at the order in which you do things',
        'Look closely at the smallest details and amplify them',
        'Make it valuable by putting it in an exquisite frame',
        'Make a sudden, unpredictable shape',
        'Only one element of each kind',
        'Reverse',
        'Tidy up',
        'Turn it upside down',
        'Use an unacceptable color',
        'What would your closest friend do?',
        'Work at a different speed',
        "Add black",
        "The right thing at the wrong place",
        "The wrong thing at the right place",
        "Use your non-dominant hand",
        "Stretch it out",
        "Make it huge",
        "Make it tiny",
        "Only shades of grey",
        "Make a collage",
        "No straight lines",
        "Only one single line",
        "Make it heavy",
        "Go outside",
        "Color outside the lines",
        "Create using nothing but letters",
        "Create, then destroy, then repair",
    ]
};

export default oblique;
